### ISSUE TITLE
Running examples issues

### ISSUE THREAD

**Issue by sguysc** [StanfordASL/Model-Mismatch#1]
EDIT
(sorry for the first question, I had too many tabs open in my browser
and it referred to a different repo)

I'm having trouble running the examples right after cloning:
1. Dubins car - Cannot find a solution for _solve_DUBINS_start_1_
right on the first try in file initialize_Dubins.m.

2. Car5D - there were issues regarding dimensions when computing 
`dV_dr = subs(diff(V,rt),rt,c)*Jc;`
after fixing that (with a couple of transposes), 
`Iteration: 3 `
`Solving Controller (1)...failed `
`Step 1:(0:-Inf), gamma: 0.000000 `
`Solving Check (1)...solved, u_s: 0.000000 `
`Solving Check (2)...failed`
`Error using svd`
`Input to SVD must not contain NaN or Inf.`
`Error in Ellipse_plot (line 65)`
`[U D V] = svd(A);`
`Error in proj_Ellipse (line 13)`
`h = Ellipse_plot(Ap*(1/bound),center,N,c,0.2,th);`
`Error in car5D (line 205)`
`proj_Ellipse([1:2],E_sol,1,[0;0],30,'r')`
I get the same NaN issues when just running the sim file.
 
3. Plane8D - same problem as with the Car5D regarding the transposes.
Other than that, it works after I upgraded Mosek from 7 to 9.

I'm running Ubuntu 16.04, with Matlab 2018b, Mosek 9.0, spotless latest.

**Comment by ssingh19** [comment]
Hello, 

1. Can you tell me where sim_p2f is called? I have not been able to find any reference to it. The dependencies of Model-Mismatch are only spotless, Mosek, and MPT 3.0. 
2. There is no Van der Pol example in this repo so I'm not sure what you have downloaded. 
3. As for msspoly.subsref, no changes should be necessary. The spotless repo should be good to go as is. The only additional msspoly related function is the mss2fnc.m function provided in the auxiliary directory. From a quick glance, it accomplishes the same purpose as sim_p2f. I recommend using the provided mss2fnc.m for converting an msspoly object to a MATLAB function. Examples of its use can be found in any of the 4 cases studied, e.g., https://github.com/StanfordASL/Model-Mismatch/blob/87a8331fd5ea1df58fa805dac3f036065743e81a/Car_5D/car5D.m#L189-L190

Best,
Sumeet

**Comment by ssingh19** [comment]
So, SOS is pretty finicky. I set the initializations to be the exit solutions I computed, which may not play nicely with MOSEK tolerances. I am not surprised therefore that switching from Mosek 7 to Mosek 9 helped resolve some issues. I got big improvements going from Mosek 7 to Mosek 8, where they improved upon these tolerance issues in the SDP solver. 

Re: Dubins - disable the load call in the initialize_Dubins routine (lines 13-14), and uncomment the randomized guess (lines 10-11). This should allow you to get stable iterations; the full initialization algorithm should terminate in about 4-5 full iterations (of K and V subproblems). 

Re: Car5D the saved solution is actually stable. There's nothing special about the numbers in line 9 - you can play with it if you want to initialize with the guess. I re-cloned the code and made no changes. There should be no dimension issues. If you want, try putting a breakpoint at that line and see what "diff(V,rt)" gives you. It should be a row vector (and it should have called the msspoly version of 'diff'). Make sure you didn't accidentally overwrite anything else in Car5D.m. All dimensions should be correctly defined. 

I just ran Car5D with the saved initial guess. Initialization exited after first K problem; main algorithm took 3 full iterations. On iteration 4, the 2nd K subproblem failed, which is OK. So it took the last stable solution (from Iteration 3 V subproblem) and ran it successfully through the check code. 

You need to have 3 successful "solved" statements from the check code in order to not have NaNs at the end. The whole reason the check code exists is because SOS is so finicky ;)
